version: "3.9"
services:
  db:
    image: postgres:10.9
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    volumes:
      - db_data:/var/lib/postgresql/data

  web: &web
    build: .
    command: bash -c "rm -f ./tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - ./config/database.yml.sample:./config/database.yml
    environment: &envs
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_HOST: db
    ports:
      - "3000:3000"
    depends_on:
      - db

  web-next:
    <<: *web
    environment:
      <<: *envs
      BUNDLE_GEMFILE: Gemfile.next

# Declare the volumes that our application uses.
volumes:
  db_data:
